### ISSUE TITLE
Data Table lost dynamic width adjustment on upgrade

### ISSUE THREAD

**Issue by knight37x** [Teradata/covalent#1018]
### Do you want to request a *feature* or report a *bug*?
bug

#### Bug Report
Since Covalent upgrade from beta.6 to 1.0.0-rc.0 column widths of data tables are evenly split between all columns. This even happens if one column contains long strings and all others only tiny ones. I know you can set column widths but I'd much prefer the old dynamic "space allocation system"
Now (if you don't set forced line wrapping to emphasize):
![image](https://user-images.githubusercontent.com/5444004/33755255-2e4d25c2-dbf0-11e7-9b34-76017c692d9f.png)
Before: 
![image](https://user-images.githubusercontent.com/5444004/33755265-3b9ac96e-dbf0-11e7-880f-6b74612707f1.png)

StackBlitz: https://covalent-j2rftv.stackblitz.io

Something else I noticed that might be related is the changed table DOM structure (see Pictures below): "new" covalent table (mind that each table cell element has got it's width set via css):
![image](https://user-images.githubusercontent.com/5444004/33755361-a9dd08a6-dbf0-11e7-8b4d-c6deb230a2d1.png)

#### What is the expected behavior?
Work as before in beta.6

#### What is the motivation / use case for changing the behavior?
I know that in column template you can set column widths manually but I'd much prefer dynamic width adjustment.

#### Which version of Angular and Material, and which browser and OS does this issue affect?
Angular: 5.0.0
Material: 5.0.0
Browser: Chrome
OS: Windows

Did this work in previous versions of Angular / Material?
As mentioned before it did work in Covalent beta.6

**Comment by aciccarello** [comment]
So I'm not seeing the overlapping text issue but it does seem like the columns no longer are sized to fit the text. I wonder if this is possible with virtual scrolling since the header and content rows are no longer connected.

Table rendered covalent rc.0
![covalent data table with equal widths](https://user-images.githubusercontent.com/11273838/33756150-6009e6e8-dbb1-11e7-9d77-ffabbad31a11.png)


Here is the same example as rendered in beta.6
https://stackblitz.com/edit/covalent-issue-1018-previous

![covalent data table with adjusted column widths](https://user-images.githubusercontent.com/11273838/33756169-7bc6c342-dbb1-11e7-95d9-e1517b312c27.png)

**Comment by knight37x** [comment]
Overlapping only happens if there is no space where text can linewrap: Adjusted the example: https://stackblitz.com/edit/covalent-j2rftv

**Comment by aciccarello** [comment]
Ah, that makes more sense. The old implementation makes the table scroll horizontally if it gets too wide for the page. I've updated the beta.6 example to show.

**Comment by emoralesb05** [comment]
This is not a bug, this is by design since with virtual scroll not all the rows get rendered at the same time so the cells dont know which one is the longest one.. before (when we didnt care about this kind of thing) it was just using the native table cell widths.
