### ISSUE TITLE
Remove covalent/core dependency 

### ISSUE THREAD

**Issue by debben** [Teradata/covalent#123]
#### Feature Request

Remove the dependency on @covalent/core listed in src/platform/http/package.json
#### What is the motivation / use case for changing the behavior?

In the other sources for the @covalent/http package, there is nothing that explicitly depends on @covalent/core package. For those that are trying to consume @covalent/http standalone and just for the features it offers such as an HttpInterceptorService, npm ends up fetching much heavier dependencies such as angular2-material.

**Comment by emoralesb05** [comment]
Yeah, you are definitely right, the reason we had core as a dependency, is cause core has all the angular dependencies, but `http` doesnt need `material`.

Having said that, before we were forcing the versioning to be fixed (since it was beta/rc), but since angular has gone stable for a while now, we might change this to be a `peerDependency`.

**Comment by emoralesb05** [comment]
Done with https://github.com/Teradata/covalent/pull/136
