### ISSUE TITLE
Undocumented breaking change tdToogle and tdFade

### ISSUE THREAD

**Issue by DaSchTour** [Teradata/covalent#1269]
#### Bug Report

StackBlitz template: https://stackblitz.com/edit/covalent

#### What is the expected behavior?
tdToggle and tdFade are still directives exported by CovalentCommonModule

OR

there is a documented breaking change with suggested migration

#### Which version of Angular and Material, and which browser and OS does this issue affect?

occured with 2.0.0-beta.4

**Comment by DaSchTour** [comment]
I found the issue that cause this #1260
I don't understand why this is removed so hard without any notice instead of deprecating it and removing it at a later time.
This makes migration really frustrating.

**Comment by kyleledbetter** [comment]
@emoralesb05 had a good reason bc of Angular changes and can comment more, but the breaking change was documented in the changelog https://github.com/Teradata/covalent/blob/develop/docs/CHANGELOG.md#breaking-changes

**Comment by emoralesb05** [comment]
I apologize for this, we actually deprecate them around 1.5/2 months ago, but it was my mistake since we did it after beta.3, not before beta.3 like i thought.

We decided to do this since we are focusing on provided animations in a more consumable fashion and since the programmatic animations also have lots of issues..

The migration is actually pretty straight forward and im gonna add it into the changelog

before:
```
<div [tdToggle]="boolean">
<div [tdFade]="boolean">
```

after:
typescript:
```
import { tdCollapseAnimation, tdFadeInOutAnimation } from '@covalent/core/common'
...
  animations: [ tdCollapseAnimation, tdFadeInOutAnimation ],
})
```
html:
```
<div [@tdCollapse]="boolean">
<div [@tdFadeInOut]="boolean">
```

**Comment by jeremysmartt** [comment]
Closing, in changelog
