### ISSUE TITLE
Markdown incorrectly warns about sanitizing html

### ISSUE THREAD

**Issue by Enngage** [Teradata/covalent#1289]
Hi,

When I'm using content from Markdown text editor `(td-text-editor)` in Markdown `(td-markdown)` I get following warning whenever I add any heading to editor. It does not happen when using other markdown elements, only headings as far as I can tell. Strangely, the content I pass to td-markdown does not contain any html at all so I don't think this should be logged at all.

> core.js:11261 WARNING: sanitizing HTML stripped some content (see http://g.co/ng/security#xss).

**Comment by emoralesb05** [comment]
`td-markdown` is the one doing the sanitation when rendering the html since it parses it to html before injecting it.. that warning only appears in `dev` mode and will not appear on production.

Its stated in the README.

https://github.com/Teradata/covalent/tree/develop/src/platform/markdown#tdmarkdowncomponent-td-markdown

**Comment by Enngage** [comment]
Yeah, I' ve seen that, but the question is why? There is no html and it
happens only with heading tags.

**Comment by emoralesb05** [comment]
It happens on any change because internally the markdown takes the `markdown language` and parses it into `html` which then gets sanitized before being injected into the DOM to prevent XSS.

Its an internal process.

**Comment by Enngage** [comment]
No, it doesnt. If I dont add any headings, but make text for example bold
or italic, it doest display any warnings.
