### ISSUE TITLE
[Bug] Covalent Dynamic Forms: Value fetched from Number type control returned as String

### ISSUE THREAD

**Issue by monalikabiswas** [Teradata/covalent#1334]
#### Bug Report

I am working with Covalent Dynamic Forms where i have a "Number" type control.
But on trying to fetch the value from the control its giving me data as "string" like "20" and not numeric like 20...

check plunker
https://stackblitz.com/edit/covalent-d9ouef

#### What is the expected behavior?

It should return numeric value

#### Which version of Angular and Material, and which browser and OS does this issue affect?

Did this work in previous versions of Angular / Material?

**Comment by richavyas** [comment]
Hi @monalikabiswas , this seems to be an issue with angular itself. Dynamic forms use `matInput` internally and `type` issue exists not just on `matInput` but also for regular input like `<input [type]`. Here is the corresponding angular issue: 
https://github.com/angular/angular/issues/13243 
Once it is fixed in angular, it should automatically be fixed in covalent.
