### ISSUE TITLE
Question: Release/Feature plan

### ISSUE THREAD

**Issue by asaph26** [Teradata/covalent#139]
Would it be possible to share some sort of a feature roadmap/release schedule?

**Comment by kyleledbetter** [comment]
Hi @asaph26 sorry for not having our milestones updated https://github.com/Teradata/covalent/milestones

Alpha 0.9 is coming out friday or monday https://github.com/Teradata/covalent/milestone/5 with Huge data-table updates, search box component, pagination component, expansions & stepper bugfixes & Angular 2 version update and hopefully Angular-Material2 update

Alpha 0.10 will be 3-4 weeks after that with massive D3 chart updates getting the td-charts to be ready for others to add chart-types to it (and all the core features like chart tooltips, etc). We'll also add dynamic JSON driven Forms. < this will hopefully be the last Alpha since we want to be feature complete before Beta.

Beta releases will go on in Q1 2017 fixing bugs, integrating upstream releases from Angular-Material2, and ng2.

The goal is to get to RC & Stable at the end of Q1. We'll have some internal meetings for new features based on internal product requests and external github feature requests.

**Comment by asaph26** [comment]
Thanks for the quick reply. This is awesome. Looking forward to it. I am closing this for now. I think it would be awesome to add a pointer in the README so people get to it.

**Comment by kyleledbetter** [comment]
Agreed we will do that
