### ISSUE TITLE
Query Lazy Loading missing md-icon

### ISSUE THREAD

**Issue by chrizy** [Teradata/covalent#154]
possible bug? Query.

Just trying this framework out with Lazy loaded modules and getting the following error on lazy routes. normal routes load OK.

Error
**if 'md-icon' is an Angular component, then verify that it is part of this module.**

All Material 2 objects, I would expect to be loaded in the root NgModule using .forRoot()?

Thanks
Chris

**Comment by emoralesb05** [comment]
Do you have a repo and branch we can check the code or something? Would like to dive into this a little bit and replicate it.

**Comment by chrizy** [comment]
Hi,
I've created this https://github.com/chrizy/covalent-quickstart

In the left hand menu select Lazy and it will load LazyModule, which contains a test component with a md-card

thanks

**Comment by chrizy** [comment]
seems to work if I add this to the lazy module

import { MaterialModule } from '@angular/material';
@NgModule({
    imports: [
        MaterialModule

is that right, as you don't need to import this as the app.module level?

**Comment by emoralesb05** [comment]
Awesome, will check it out, and get back to you if i find anything.

**Comment by emoralesb05** [comment]
Ok, so i understand the problem now. (got confused with the lazy loading thing)

Yes, you do need to re-import all the modules needed in a sub-module since every module is an encapsulated environment of components.

So in `lazy.module.ts` you need to add `CovalentCoreModule.forRoot()` as import (which has `MaterialModule` inside)

For example in covalent: 
https://github.com/Teradata/covalent/blob/develop/src/app/components/components/components.module.ts#L60-L72

We have 4 submodules (this is the components.module.ts) and we have to re-import everything..

This is because `imports`, `declarations`, `providers` and stuff like that are `not` shared between modules to allow Applications to scale easier. (modularity)

I think we need to add sub-module examples in `covalent-quickstart` to make it easier for people to do so.

**Comment by StefanSinapov** [comment]
@emoralesb05 I'm not sure this isn't a typo, but you don't want to import `CovalentCoreModule.forRoot()` in every feature module, you should import just `CovalentCoreModule`.

**Comment by chrizy** [comment]
agreed, from reading the docs a bit more, .forRoot() should not be used in a feature module, 
Thanks for the help.
Now working..

**Comment by emoralesb05** [comment]
Awesome. 
So yeah, i didnt know providers were shared haha, so there is no need for the `forRoot()` in a sub module

Closing this issue since it wasnt covalent related.
