### ISSUE TITLE
Autocomplete doesn't work in latest Safari version

### ISSUE THREAD

**Issue by leolorenzoluis** [Teradata/covalent#165]
### Do you want to request a *feature* or report a *bug*?
Bug

#### Bug Report

1. Go to https://teradata.github.io/covalent/#/components/chips
2. Start typing where it says autocomplete input is supported
3. Autocomplete is not showing, it just adds chips

#### What is the expected behavior?
Show autocomplete

#### Which version of Angular and Material, and which browser and OS does this issue affect?
Whatever the demo uses, latest safari version and macOS

Did this work in previous versions of Angular / Material?
No idea.

**Comment by emoralesb05** [comment]
Which version specifically of safari does this happen?

**Comment by kyleledbetter** [comment]
I'm seeing it in Safari 10.0, the autocomplete dropdown doesn't work:
![image](https://cloud.githubusercontent.com/assets/867883/20546616/00ee4e66-b0dc-11e6-9a7e-7ab2adc3e5f6.png)

Native HTML5 input list isn't supported by Safari... I'm debating what we want to invest since angular-material2 is building this https://github.com/angular/material2/issues/117

**Comment by leolorenzoluis** [comment]
@emoralesb05 10.0.1

@kyleledbetter Do you mean, you're just going to wrap TeraData components [Autocomplete] with Material 2?

**Comment by emoralesb05** [comment]
true, `md-autocomplete` is coming so we might replace ours with that one inside `md-chips`.

**Comment by kyleledbetter** [comment]
@leolorenzoluis the goal of Covalent is to build on top of angular-material2 and add to it, but in a few cases like this we needed a component before they had it so if their version meets all needs we'll retire ours, or if we need extra features we'll wrap it as you suggest

**Comment by leolorenzoluis** [comment]
@kyleledbetter That's awesome, I am in the stage of evaluating Teradata to be used as a UI component as Material 2 is lagging behind from 1. How is the support for UI components? Is this free or there will be enterprise grade support in the future?

**Comment by kyleledbetter** [comment]
No plans for enterprise support or commericalism. This is a traditional open source developed and community supported project that's free and licensed under MIT like everything it's built on

**Comment by leolorenzoluis** [comment]
@kyleledbetter Just curious, you have more domain knowledge than me, but given that Material 1 has at least complete and stable API/components. Why doesn't Teradata just scrap existing Material 1 and just come up of a simple API such as for Autocomplete?

**Comment by leolorenzoluis** [comment]
Hmm, then given Teradata is just building on top of Material 2, why won't Teradata just branch off Material 2 rather than having a separate repo? More exposure for people who contribute in Material 2 it self and less hassle marketing this UI component? All they have to do is branch from it, and more over you get the benefit of likely merging whatever API design you use now that are currently not available in M2?

**Comment by kyleledbetter** [comment]
Not sure what you mean by ` just branch off Material 2 rather than having a separate repo` < we include angular-material2 as a dependency just like any other node repo, just as we include angular2 itself. We don't want to replace any of those things or be responsible for maintaining that part of the code base. We want to build on TOP of all their hard work and add all the things missing to make a full-featured application.

Let's keep this issue focused on Autocomplete in Safari and head to our Gitter chat if you'd like to have philosophical debates about our architecture decisions :) https://gitter.im/Teradata/covalent
