### ISSUE TITLE
Deep imports warning on serve

### ISSUE THREAD

**Issue by Christian-TD** [Teradata/covalent#1878]
#### Bug Report

execute `npm start` and it will throw the warnings during build.
[StackBlitz example](https://stackblitz.com/edit/covalent-zim9w2)

##### Screenshots

![image](https://user-images.githubusercontent.com/52788365/151073545-54764fa8-ea8d-437a-8432-6ccad5852055.png)

#### What is the expected behavior?

To supres all warnings.

#### What is the motivation / use case for changing the behavior?

As a production package, shouldn't throw any warnings.

#### Which version of Angular and Material, and which browser and OS does this issue affect?

Angular 11.2.14
Angular Material 11.2.13
Covalent 3.1.2

**Comment by owilliams320** [comment]
Hi @Christian-TD thanks for your submission. It looks like the `@covalent/echarts` warnings can be solved. but the `@covalent-editor` warning is due to way we import the dependant monaco package uses a ESM module. This prevents the consumer from packaging every language monaco supports which would bloat any consuming app. 


My suggestion for warning you dont want to see can be suppressed in the build configuration in your `angular.json`

see https://angular.io/guide/build#configuring-commonjs-dependencies

**Comment by Christian-TD** [comment]
> Hi @Christian-TD thanks for your submission. It looks like the `@covalent/echarts` warnings can be solved. but the `@covalent-editor` warning is due to way we import the dependant monaco package uses a ESM module. This prevents the consumer from packaging every language monaco supports which would bloat any consuming app.
> 
> My suggestion for warning you dont want to see can be suppressed in the build configuration in your `angular.json`
> 
> see https://angular.io/guide/build#configuring-commonjs-dependencies

Hi @owilliams320 thanks for the tip, but did not work. After some googling and trials, finally got them removed by creating the file `ngcc.config.json` with 
```json
module.exports = {
    packages: {
        '@covalent/code-editor': {
            ignorableDeepImportMatchers: [
                /editor\//,
            ]
        },
    },
};
```
