### ISSUE TITLE
NgFor does't work for stepper

### ISSUE THREAD

**Issue by Layyy** [Teradata/covalent#200]
- Bug Report
If you use *ngFor in stepper it fails and website is down with the following error

"EXCEPTION: Error in ./TimelineComponent class TimelineComponent - inline template:27:4 caused by: The [td-step] component needs to have a [td-steps] parent component to work."

This code I am using

`<td-steps (stepChange)="change($event)" mode="vertical">
  <td-step *ngFor="let item of items">
    {{item.name}}
  </td-step>
</td-steps>`

- What is the motivation / use case for changing the behavior?

The data in stepper won't be always the same for me so I need to generate it.

**Comment by emoralesb05** [comment]
This is because there is a validation to not allow stand-alone steps when rendering a page.. but `ngFor` is renders it after it, so its trying to validate against that. (same issue would happen if used with `ngIf`)

We are probably going to remove this validation, since its better to just leave it flexible to be able to add steps on the fly with either `ngFor` or `ngIf`.
