### ISSUE TITLE
Ng serve failed with error

### ISSUE THREAD

**Issue by Layyy** [Teradata/covalent#237]
Bug Report
After ng serve build fail with this error "Uncaught Error: Can't construct a query for the property "_input" of "TdSearchInputComponent" since the query selector wasn't defined."
I just updated my version from 9.1 to 10.2 and this happend. Any suggestion where the problem could be? 
I am only using the covalent core for a stepper.

**Comment by emoralesb05** [comment]
Hmm, there is was an issue opened for this, but they closed it. So, my suggestion for now would be to load the pre-compiled `platform.css` instead of the `platform.scss`. 

We are gonna look into this issue.

**Comment by emoralesb05** [comment]
Oh wait... i thought this was a `scss` issue. We are going to try to replicate it and see what the problem might be.

**Comment by emoralesb05** [comment]
So we already replicated this, and it happens when you have a previous version of `@angular/material` installed in your `node_modules`.. since `TdSearchInputComponent` relies on a `TdInputDirective` class that only exists in `@angular/material/2.0.0-beta.1`

`@covalent/core@0.9.1` was using `@angular/material/2.0.0-alpha.10`
`@covalent/core@0.10.2` now uses `@angular/material/2.0.0-beta.1`

So clear the `node_modules` with `rm -rf node_modules dist tmp` and ensure any other dependency doesnt install a prev version.

**Comment by emoralesb05** [comment]
Closing since it was a version issue and no other comments havent been made.
