### ISSUE TITLE
[Feature] Integrate @angular/flex-layout

### ISSUE THREAD

**Issue by d3viant0ne** [Teradata/covalent#239]
#### Feature Request

I've integrated flex-layout successfully in one of my work apps already and have been impressed with how much it simplified the layout portion of adding new features. Seems like it would be a good fit here assuming you are interested.

Also worth noting that the `MatchMediaObservable` has all sorts of cool possibilities for UX.

#### What is the motivation / use case for changing the behavior?
In my opinion `Responsive layout is where free time goes to die` so anything that can simplify that for developers is a good thing :)

#### Which version of Angular and Material, and which browser and OS does this issue affect?
The proposal would be to add the as yet, unreleased @angular/flex-layout v2.0.0-beta.2 as it has two needed bug fixes and introduces a custom break points feature.

##### Other information
I'm happy to do the work assuming all the stake holders want to go this route. The end result being to get back to exactly where this is now just using flex-layout to get there.

**Comment by kyleledbetter** [comment]
Thx @d3viant0ne we've been keeping an eye on flex-layout and it looks great. We brought over the flex layout from angular-material v1 since v2 didn't have anything at first and can't live without it.

This is tricky since every bit of Covalent depends on the current flex layout and every single product/app using Covalent will have to update every bit of html.

I'm thinking we bring in flex-layout and keep them living together for a while and slowly deprecate our existing layout while folks transition over. Hoping there's no major conflicts.

`MatchMediaObservable` definitely has cool UX implications.

So that all being said, yes we'd love for you to submit a PR so we can start testing, thanks so much for the offer!

**Comment by emoralesb05** [comment]
We will probably start with this as soon as `beta.1` is released. 😄  We can migrate slowly and give priority to any modules that have conflicts between our `flex` and `@angular/flex-layout`

**Comment by d3viant0ne** [comment]
@emoralesb05 - FYI @ThomasBurleson landed custom breakpoints and reworked the `ObservableMediaService` a bit. At this point `@angular/flex-layout` had feature parity+ with the `MediaService` currently in Covalent so everything is g2g on the library side.

Just @ me if you want some extra bandwidth updating features in Covalent to use `fxFlex`

**Comment by emoralesb05** [comment]
Awesome @d3viant0ne ! I had not seen that the `beta.4` release was out since the `changelog` hasnt been updated in a while. 

Will @ you for sure 😄 , i am liking this one in particular https://github.com/angular/flex-layout/pull/147 since its exactly the roadmap we wanted for the `tdMediaToggleDirective`.

**Comment by ThomasBurleson** [comment]
Also see https://github.com/angular/flex-layout/wiki/Custom-Breakpoints

**Comment by emoralesb05** [comment]
Thanks @ThomasBurleson ! Will check it out since we want to include this as soon as possible 😄

**Comment by emoralesb05** [comment]
@d3viant0ne Started the initial PR to include it as part of covalent for next release 😄 .
