### ISSUE TITLE
Feature: Module Loading with webpack instead of cli

### ISSUE THREAD

**Issue by richavyas** [Teradata/covalent#246]
#### Feature Request

Support covalent module loading using webpack. 
Covalent current module loading works with cli and this feature is to add support to load with webpack instead of cli.

**Comment by sachinofficial** [comment]
@richavyas in my ng-2 application I am not able to use the library with `webpack-2.2.0-rc.3`. As the HTML templates aren't being picked up because they are referencing to relative path from the project root folder, any idea how to get around this for now until the feature is implemented?

I tried to load `index.js` with `NormalModuleReplacementPlugin` as well but got this error 
`ERROR in ./~/@covalent/core/common/common.module.ts
Module build failed: Error: Final loader didn't return a Buffer or String`

my `NormalModuleReplacementPlugin` config is this
`new NormalModuleReplacementPlugin(
                /@covalent(\\|\/)core/,
                helpers.root('node_modules/@covalent/core/index.js')
            )`

I would suggest to use `require()` in the component definition to load styles and template as a permanent fix.

`
@Component({
  providers: [ TD_DATA_TABLE_CONTROL_VALUE_ACCESSOR ],
  selector: 'td-data-table',
  styles: [require('./data-table.component.scss')],
  template: require('./data-table.component.html'),
  changeDetection: ChangeDetectionStrategy.OnPush,
})
`

Also what's the timeline for this feature to be released?

**Comment by emoralesb05** [comment]
Thanks for the suggestion, but thats not really the proper fix for this. 

We have our `*.umd.js` files that have all the resources inlined and bundled, so they are agnostic of what `bundler` you are using. (webpack, broccoli, etc etc)

We just have to do some tweaks and properly document how to include `covalent` in a `webpack` project without the usage of the `angular-cli`.

So even though it says `feature` in the issue's title, its more of a `test` and properly `document` thing.

**Comment by sachinofficial** [comment]
@emoralesb05 any idea on when this will be released?

**Comment by emoralesb05** [comment]
This will be one of the next steps towards `beta.2`.

**Comment by emoralesb05** [comment]
Some stuff to check out for webpack support.

https://docs.npmjs.com/files/package.json#main

+ usage of `typings` and `module` properties in `package.json`.

How they act in `CLI` vs `webpack`

**Comment by emoralesb05** [comment]
Also to leverage the `~` in the imports, we have to look into https://github.com/jtangelder/sass-loader, since people need to use it with webpack.

**Comment by emoralesb05** [comment]
btw @sachinofficial , can you try this for now?

```
new NormalModuleReplacementPlugin( /@covalent(\\|\/)core/, helpers.root('node_modules/@covalent/core/core.umd.js') )
```

So you load the `umd` file, instead of the `index` file.

**Comment by emoralesb05** [comment]
Closing this since there are people using webpack already with covalent without issues.
