### ISSUE TITLE
Chips/Autocomplete Lazy Load of Suggested Items

### ISSUE THREAD

**Issue by crain** [Teradata/covalent#252]
#### Feature Request
Add the possibility to lazy load suggested items for the chips/autocomplete component.

https://teradata.github.io/covalent/#/components/chips

#### What is the motivation / use case for changing the behavior?
Currently the component needs all data beforehand and there is no possibilty to hook in to user inputs and refetch data based on the input.

Possible use case:
User Form where the user has to select multiple items out of a large dataset.
The data can't be loaded before as the browser memory would blow up.

**Comment by emoralesb05** [comment]
So, we need to externalize the inputs events somehow... now, with the way `md-autocomplete` will work in `@angular/material`, this might change a little bit so lets start by discussing things in this issue.

**Comment by emoralesb05** [comment]
I think that we can create a method to get to the input element:

e.g.
```
@ViewChild(TdChipsComponent) chips: TdChipsComponent;

ngOnInit(): void {
  this.chips.getInputElement().onChange((event) => {
    // do your loading here
  });
}
```

OR

```
<td-chips #chips (keydown)="loadItems(chips.getInputElement().value)">
</td-chips>
```

That way people can get to the internal element and its event hooks without having to create `n` number of `EventEmitter`s. 

Although, its nice if we can at least handle 2 or 3 general events.

```
<td-chips (inputChange)="loadItems($event)">
</td-chips>
```

And so, just thinking out loud. 

Which we might have to start creating methods to access the underlying component for most implementations either way, since there are cases where you want that.

**Comment by emoralesb05** [comment]
This PR https://github.com/Teradata/covalent/pull/459 will be the base for this feature.

**Comment by emoralesb05** [comment]
https://github.com/Teradata/covalent/pull/626 will take care of this 😄 .
