### ISSUE TITLE
[Component] Data-List (responsive list version of data-table)

### ISSUE THREAD

**Issue by richavyas** [Teradata/covalent#260]
### Description
Data List is a feature for Managing a data list with various sub-features like: 
  - list
  - filter
  - order by
  - search
  - pagination
  - responsiveness

#### Filter
User optionally might want to see values for some columns and this filter gives a great way of enabling that e.g. various date options for a list `created/updated/last opened` can be clubbed into one column using this filter and the column header can be rendered as a select box for those date columns.

#### Order By
On the click of `asc/desc` icon on a column, the list can be ordered by.

`<td-data-list>` is a tag for creating List. It has the following sub-tags for columns and various features:
  - `<td-data-list-column>`
  - `<td-data-list-search>`
  - `<td-data-list-pagination>`

##### `<td-data-list>`
List tag consists of the following parameters:
  - list title
  - optional icon for the list
  - dynamic data to be rendered by the list

##### `<td-data-list-column>`
Column tag consists of the following parameters:
  - name
  - icon : optional
  - flex : value for the column layout
  - columnOptions : comma separated list of options for filter-select-box
  - sort : if sorting is required on this column

##### `<td-data-list-search>`
List-search tag consists of the following parameters:
  -  columns : columns to be searched

##### `<td-data-list-pagination>`
List-pagination tag consists of the following parameters:
  - pageSizes : record counts per page
  - totalRecords : total number of records

Usage:

```
<td-data-list
        [listTitle]="[string]"
        [listIcon]="[icon from Covalent icons]"
        [data]="[data to be rendered]">

        <td-data-list-column [name]="[string]" [icon]="[icon from Covalent icons]" [flex]="[number]"
                [columnOptions]="[comma separated list of options for filter-select-box]" [sort]="[true]">
        </td-data-list-column>

        <td-data-list-search [columns]="[columns to be searched]"></td-data-list-search>

        <td-data-list-pagination 
                [pageSizes]="[number of records to be shown during pagination]" 
                [total]="[maximum number of records to be rendered on a page]">
        </td-data-list-pagination>

</td-data-list>
```

![data-list](https://cloud.githubusercontent.com/assets/4469548/22125319/0e6aa7bc-de48-11e6-8d4d-9c036b26b552.gif)

**Comment by emoralesb05** [comment]
So, just to keep start the flow here:

### Component reuse and flexibility

The first thing that comes into mind is.. (without thinking about implementation specifics) I would reeeeally like if we could leverage our `td-paging-bar` and `td-search-box` the same way we do it for the `td-data-table`. (also i would rather leave the `[title]` out of it)

e.g.

```html
<div layout="row">
  <span>Title</span>
  <td-search-box (debounce)="search($event)" flex></td-search-box>
</div>
<td-data-list
        [listIcon]="[icon from Covalent icons]"
        [data]="[data to be rendered]">

        <td-data-list-column [name]="[string]" [icon]="[icon from Covalent icons]" [flex]="[number]"
                [columnOptions]="[comma separated list of options for filter-select-box]" [sort]="[true]">
        </td-data-list-column>
</td-data-list>
<td-paging-bar [total]="20" (pageChange)="page($event)"></td-paging-bar>
```

This because we would want the `data-list` to be agnostic of whats handling the search and paging. Since the paging could be done by outside filters, a different `paging` component`, etc etc.

### Difference between `data-list` and `data-table`

So the biggest difference is that a `data-table` we know before hand that each value will belong to a specific cell. This is not true for a `data-list` since the user might want `n` values in 1 `"cell"`.

e.g.

```html
<md-list-item>
  <h3 md-line>Line 1</h3>
  <p md-line>Line 2</p>
  <span md-line>Line 3</span>
  <span>Different Cell</span>
</md-list-item>
```

So we have to think how we can provide that flexibility and still make the `data-list` useful.

Also, a way to add different icons, not just `1` icon for all rows. and any element or component at any point (buttons, links, tooltips, etc) with the use of **templates**

### Column widths

We have to calculate how to fit the columns so they are aligned.

### Selection

Possible way to select `n` number of rows?

### List vs Nav List

We have to also think about the different types of lists and their usages. How will that fit inside the data-list, since i might want a responsive list that serves as navigation (job list)

### Responsive

Now we have the `md-select` that the user can pre-populate the columns (which is fine).

But i think it would be better if depending on a configuration or order, the columns would automatically populate that `md-select` as the screen stops being able to fit them or depending on a screen breakpoint.

Also, there might be some columns that i just wouldnt want in that `md-select`.. so those i would wanna hide automatically depending on a screen breakpoint. 

This without using a `media.service` inside (ideally) if possible.

There are just so many different ways a user can represent a data-list, so we have to think about this carefully.

**Comment by asaph26** [comment]
Is this something that is coming before RC?

**Comment by emoralesb05** [comment]
We are trying to use this in our internal products to see if it makes sense. But for the most part we are going to try adding lots of `data` components going forward since our products specialize in big data.

**Comment by emoralesb05** [comment]
The team decided to add an example of a `data-list` since its just a wrapper on `md-list`, `virtual-scroll` with pagination and sorting

https://teradata.github.io/covalent/#/design-patterns/management-list
