### ISSUE TITLE
TdExpansionPanel expand="false" doesn't work

### ISSUE THREAD

**Issue by ericis** [Teradata/covalent#318]
**Covalent Core 1.0.0-beta.1-1**

#### Bug Report

A simple `<td-expansion-panel expand="false">Hello</td-expansion-panel>` is always expanded. It should be collapsed on load.

http://plnkr.co/E0SXDbhjAx2oHjWngORx

#### Which version of Angular and Material, and which browser and OS does this issue affect?

Windows 10

All browsers

angular-cli: 1.0.0-beta.28.3
node: 6.9.4
os: win32 x64
@angular/common: 2.4.5
@angular/compiler: 2.4.5
@angular/core: 2.4.5
@angular/forms: 2.4.5
@angular/http: 2.4.5
@angular/platform-browser: 2.4.5
@angular/platform-browser-dynamic: 2.4.5
@angular/router: 3.4.5
@angular/compiler-cli: 2.4.5

**Comment by emoralesb05** [comment]
Angular does not know that `false` is actually a boolean, its taken as a string which then is evaluated to `true` since its something not empty..

To achieve what you want, you have to do it this way so its evaluated as boolean:

```
<td-expansion-panel [expand]="false">
```

Now, its true that we might need to check for `false` string (coerce it like material does), but this would be a lower priority bug since normally you would use a `boolean` property and not a hardcoded string.

**Comment by diegoviscovig** [comment]
Hi, the variable expand never change status, I created a plunker http://plnkr.co/edit/MBWN0uxJZ8UTOrdrPtfj?p=preview, and I assigned this property to [sublabel], and this is always true.

Thanks, EXCELLENT PLATFORM FOR EXTENDS MD!!

**Comment by emoralesb05** [comment]
Its because its an input, its not binded in a 2-way fashion.

You would need to add something like this: 

```
<td-expansion-panel [sublabel]="expand" [expand]="expand" (expanded)="expand = true" (collapsed)="expand = false">
    <p>Hello, this is an example of a working expansion panel</p>
  </td-expansion-panel>
```

There might be a need for an event thrown on open-close to make it simpler like: 

`(toggled)="expand = $event.expanded"` or something like that
