### ISSUE TITLE
Make the chip suggestions look & behave like a material select in angular 1

### ISSUE THREAD

**Issue by thekalinga** [Teradata/covalent#342]
#### Bug Report

1. Currently chips suggestion dropdown looks complete off from the actual material spec
2. The backspace/left arrow does not select the previous item in the list + left & right arrow navigation does not work
3. Searching does not auto select the first item
4. Within the already selected chips, using arrow/click if you select a chip, `delete` button should delete the chip & make it available in the autocomplete

#### What is the expected behavior?

The suggestions should look & behave like material select in angular1

#### What is the motivation / use case for changing the behavior?

To keep it consistent with material style. The demo can be found here https://material.angularjs.org/latest/demo/chips

**Comment by emoralesb05** [comment]
The reason it looks `complete off` from the actual material spec its because its a native `datalist`, we are currently waiting on `material` to use the `md-autocomplete`.

Once `md-autocomplete` is released, we are gonna revisit and polish the chips module and take into consideration the `a11y` enhancements mentioned in 2 and 4.

There has already been mentions here:
https://github.com/Teradata/covalent/issues/215 and https://github.com/Teradata/covalent/issues/165

**Comment by thekalinga** [comment]
Should I close this/keep it open?

**Comment by kyleledbetter** [comment]
We'll close this since it's coming. Track their progress here https://github.com/angular/material2/projects/7
