### ISSUE TITLE
[Question]  micro syntax or template

### ISSUE THREAD

**Issue by BartNetJS** [Teradata/covalent#409]
The most documentation uses the micro syntax. e.g.

```
<div *ngFor="let hero of heroes; let i=index; let odd=odd; trackBy: trackById" [class.odd]="odd">
  ({{i}}) {{hero.name}}
</div>
```

the more explicit syntax is

```
<template ngFor let-hero [ngForOf]="heroes" let-i="index" let-odd="odd" [ngForTrackBy]="trackById">
  <div [class.odd]="odd">({{i}}) {{hero.name}}</div>
</template>
```
The covalent samples uses the full template syntax. 

What is your opinion (or a reason not using micro syntax)?

**Comment by emoralesb05** [comment]
Honestly, it depends a lot of what you want to achieve.

If you just want to loop though an array and populate something, then both are interchangeable.

But if you want to add more elements around the loop without an additional wrapper element, then you need <template> syntax.

e.g.

```
<template ngFor let-hero [ngForOf]="heroes" let-i="index" let-odd="odd" [ngForTrackBy]="trackById">
  <div [class.odd]="odd">({{i}}) {{hero.name}}</div>
  <md-divider></md-divider> <-- this is added every loop
</template>
```

Since what `*` in reality is just setting a `<template>` element for you.

**Comment by kyleledbetter** [comment]
Yup, mainly template gives you more flexibility, closing since this is a conversation and not an issue, btw feel free to continue the chat on https://gitter.im/Teradata/covalent
