### ISSUE TITLE
Expression has changed after it was checked.

### ISSUE THREAD

**Issue by iceman3000** [Teradata/covalent#425]
##### Screenshots or link to CodePen/Plunker/JSfiddle
HTML: http://pasteboard.co/JKOrM2ALA.png
TS: http://pasteboard.co/JKPBqvtuO.png
Error: http://pasteboard.co/JKQeyJS98.png

#### What is the expected behavior?
To not throw errors

#### What is the motivation / use case for changing the behavior?
NA

#### Which version of Angular and Material, and which browser and OS does this issue affect?
@Latest - All browsers

##### Other information
(e.g. detailed explanation, stacktraces, related issues, suggestions how to fix)
I have an angular app deployed with cli - I've included the Covalent files and copied the demo layout from the website and I get the error as seen in screenshot.

**Comment by iceman3000** [comment]
Sorry, but your reply doesn't make a lot of sense to me, probably due to my lack of understanding of all the terms you just used. I am looking to use Covalent in my project and it looks awesome, but so far out of the box I've hit a number of relatively technical snags trying to implement basic examples from the documentation. I guess what I am saying is I'd love the see the project take off and be super successful, but undocumented steps like this make it hard for simpler users to get involved. Can you please try and explain a little less technically - my understanding of angular 2 is basic, I am just learning, and/or link me to something that may help clarify. Thanks for your reply!

**Comment by asaph26** [comment]
Hi @iceman3000,
Here is my attempt at demystifying @emoralesb05 answer for you.

Angular has a change detection mechanism that it uses to detect changes and when to update the view. It offers 2 modes of this. One is the default mode which is being used in your code and the other is the OnPush mode. 

In the default mode, there is a change detection cycle that runs periodically to check if any value has changed and if there is a change, then the view is updated (The view is what you see on the browser)

Looking at your code, you are calling `this.media.broadcast()` inside the `ngAfterViewInit` lifecycle hook*. The media broadcast call in turn informs the listeners the screen width of the browser the application is loaded in.

The TdNavListComponent had a value of **over** initially, however after the media.broadcast() it was changed to **side**. This would typically not be a problem, however while running the application in the development mode, there are 2 change detection cycles running one which actually applies the changes and one after that to verify that nothing additional has changed after the previous cycle. This is to ensure that if there is a change after the previous change detection cycle, there needs to be a new call to the change detector so that it can update the view, otherwise the view is already outdated.

There are multiple ways to fix your code to get it to work. The suggestion from @emoralesb05 is to call the detectChanges method of the ChangeDetectorRef after your broadcast call.

**Not Recommended**
You can always run the app in production mode by calling enableProdMode() in your main.ts file to get rid of the error, but this means that the change detection will not be applied.

More information here
https://blog.thoughtram.io/angular/2016/02/22/angular-2-change-detection-explained.html
https://github.com/angular/angular/issues/6005#issuecomment-165905348

**Comment by iceman3000** [comment]
Hi @asaph26 
Thanks for your reply! Since posting my update earlier I trawled through angular2 docs with keywords from @emoralesb05 answer and had a play around with how .broadcast was working. Also had a friend of mine helping out too - both as unfamiliar with angular2 as each other though. We can up with this solution that seemed to work:

`  ngAfterViewInit(): void {
      setTimeout(function(media){
        media.broadcast();
      },0, this.media);
    }`

Is this a bad fix? It seems simpler than importing and creating new constructors etc?

**Comment by asaph26** [comment]
@iceman3000 That is not a bad fix in itself. It basically postpones the update to the next change detection cycle. At the end of the day, its a lot about understanding why certain things work and certain things don't.

**Comment by iceman3000** [comment]
Thanks for the help on this one guys 👍 hopefully if anyone else runs into this issue they can refer to these comments. I'll close this off now!
@asaph26 @emoralesb05
