### ISSUE TITLE
pipe autoupdate

### ISSUE THREAD

**Issue by Dj-jom2x** [Teradata/covalent#509]
is this possible  .. 

` {{ log.timestamp | timeAgo:reference }}`   that this will background updating the value over time ..? 

like when it says 1 sec ago .. every 5 sec it will update to 5 sec ago 10 sec ago ..  for chats

**Comment by Dj-jom2x** [comment]
solve i put ^_^ 	pure: false on time-ago.pipe.js ... please add that in the future :) 
`TdTimeAgoPipe = __decorate([
    Pipe({
        name: 'timeAgo',
		pure: false
    })
], TdTimeAgoPipe);`


i use it on chat box ^_^

**Comment by emoralesb05** [comment]
This was done by design since setting the `pure` parameter as false makes it trigger change detection a LOT more (hence why it works like you want it to work).

Trying to see if there is a way to get both things or a work around to trigger it when needed.

**Comment by Dj-jom2x** [comment]
for time ago that's very useful ..  pure: false is not a good idea also ( i thought its good ) .. xD in order to update ... you need a observable interval that ticks in any sec or hour or days you want ..   when observable interval is running it udpates the time ago pipe xD instant super live (ignore the any number you put in interval) ... if i send 10 chats .. you will see all the time ago is update 1 sec ago 2 sec ago 3 sec ago and so on ....  the down side XD it uses 3% cpu i saw it on chrome task manager XD 3% idle xD ..... thats why i remove interval observable .... i still leave pure: false...  it only updates if new chats are comming or if you type something on input box  now its 0% ... but still i hope someday it will be auto :) because  kinda weird to see xD 1 sec ago chat then when you trying to chat them it will update XD 10 minutes ago hahaha ..

**Comment by emoralesb05** [comment]
Yeah, totally get it 😄 . 

Will check the pros and cons and see what makes more sense for this. 👍

**Comment by Dj-jom2x** [comment]
sad haha it gets remove..

**Comment by jotatoledo** [comment]
The pipe should stay pure IMHO. Most cases in which pipes are impure is when they are influenced by a dependency that signalizes the pipe to recalculate its value, eg: service, or the arguments given to the `transform` function are intentionally mutable (this one kinda kills the purpose of a pipe though). Neither of those cases match your use case; you simple want to make it impure because the value needs to be recalculated *over time*.

For your use case, the common approaches would be IMO:
- Turn the `reference` argument into a stream. How oft does this stream emit a value depends on your requirements/implementation. You could have a stream with a frequency that decreases over time: basically the longer the stream lives, less
- Create your own impure pipe that internally uses the `TimeAgoPipe`.
