### ISSUE TITLE
[FEATURE REQUEST] Custom Dynamic Form Types

### ISSUE THREAD

**Issue by fernandobandeira** [Teradata/covalent#512]
#### Feature Request

Customize Dynamic form types.

It would be nice to create custom types for dynamic forms, this way we can use things like rich text editors and other things with this component.

Not sure what's the best aproach for this, maybe something simillar to the column customization provided by the datatable component.

**Comment by emoralesb05** [comment]
Yep, already thinking about how to approach this.

Possibly by passing a component type like `MdDialog` does it, so you can extend it as needed.

Still brainstorming about this. 😄

**Comment by emoralesb05** [comment]
Closing this in favor of https://github.com/Teradata/covalent/issues/314

**Comment by MotionComplex** [comment]
Hey there

We are using covalent dynamic forms to load and öset different values to generate word templates. 
Some metadata values like document autor, document language and the document version are sent to the application from an API-service as JSON objects, so dynamic forms can display them on the page. 
Now there are some more complex data section, which we need. For example we need a way to search for persons. Therefor our idea is, that we have an dropdown-like element which has a search function, so we can type in a search value which will be sent to an API-service. When the API-service returns the person values, we want to list them in the dropdown, so we can select one of the person values. 

We just saw that you created a project backlog item for customizing dynamic form types but it doesn't seem like something changed since September 2017. What's the current state of this backlog? Are you working on it? 
Because we really need this kind of functionality. And we guess there are a lot of other covalent dynamic forms user, which would be happy to customize the dynamic forms functionality and create custom elements.

Thank you for your response! :)

**Comment by emoralesb05** [comment]
Sorry, the team was busy with our internal projects and we couldnt handle all the requests. But now we are back on track on working on this for our 2.0.0 release. We are gonna make the issue public soon, so be ready for new components and features!
