### ISSUE TITLE
Need of accordion 

### ISSUE THREAD

**Issue by PallaviGiri** [Teradata/covalent#54]
http://demo.sodhanalibrary.com/angular/material-ui/accordion/accordion1.html
Do we have a accordion in covalent?

**Comment by uncledlm** [comment]
Covalent has expansion panels:
https://teradata.github.io/covalent/#/components/expansion-panel

**Comment by mattspaulding** [comment]
Pretty.

**Comment by kyleledbetter** [comment]
Yup, thx @uncledlm, Expansion panels are the Accordions (on steroids) of Material Design

They can be used standalone like a Collapse, but with optional label/sublabel and summaries that animate away when you delve into the full detail (since material is immersive), or they can be used in a group like an accordion

For what it's worth, we follow the Material Design official spec as closely as possible, and they cover expansions https://material.google.com/components/expansion-panels.html but not accordions

**Comment by PallaviGiri** [comment]
thanks @uncledlm
