### ISSUE TITLE
Auto colse dialog box

### ISSUE THREAD

**Issue by santhoshnv** [Teradata/covalent#680]
Is any option have auto close in dialog box, If no means what about bring that

**Comment by emoralesb05** [comment]
Autoclose? Can you elaborate on that a bit please?

**Comment by santhoshnv** [comment]
The dialog box should disappear after some seconds, like snackbar

**Comment by kyleledbetter** [comment]
Hmmm I think you should use a snackbar then. Check the official spec for dialogs 

"Dialogs always retain focus until dismissed or a required action has been taken."

https://material.io/guidelines/components/dialogs.html

**Comment by emoralesb05** [comment]
Yup, its by spec that dialogs should remain on screen until a user action.

Dialogs should be used when something happens that requires user attention, like errors and what not.

Snack bars are for things that if a user doesn't acknowledge them, it wont affect the flow.. small informative messages.

Having said that, you can do your own implementation with a `timeout` and closing it after opening it if you REEEEEEEALLY want to do it.

```
  openAlert(): void {
    let dialog = this._dialogService.openAlert({
      title: 'Alert',
      disableClose: true,
      message: 'This is how simple it is to create an alert with this wrapper service.',
    });
    setTimeout(() => {
      dialog.close();
    }, 3000);
  }
```

But we discourage people from doing this, since at that point a snackbar is a better UX and spec.

Closing this since its not spec.
