### ISSUE TITLE
Feature: message body to td-message

### ISSUE THREAD

**Issue by drakir** [Teradata/covalent#703]
Reading the documentation implies that there are support for a message body inside the td-message component, but how? I can add a "label" and a "sublabel" among with action buttons, but no markup of my own in the body.

**Comment by emoralesb05** [comment]
We designed  to allow that, but are checking to see if it really makes sense to do so since we want to keep the messages to be short and to the point.

We wanted to keep it flexible enough that would allow that in the future just in case.

So we can keep this issue open while we get into an agreement with that.

**Comment by jeremysmartt** [comment]
Need to either update the example in docs or support this behavior
