### ISSUE TITLE
How to integrate with angular material 2?

### ISSUE THREAD

**Issue by mailok** [Teradata/covalent#770]
This is my problem, i have a proyect with angular material 2, and i want use some component of covelant, there any way these two can coexist in same proyect?
because it tries to integrate them and do not get it

**Comment by jotatoledo** [comment]
If you are using angular cli, take a look here https://github.com/Teradata/covalent/blob/develop/docs/GETTING_STARTED.md

**Comment by marlonwanger** [comment]
How to use covalent with the latest version of CLI?

My Project
@angular/cli: 1.2.3
node: 8.1.2
os: win32 x64
@angular/animations: 4.3.2
@angular/common: 4.3.2
@angular/compiler: 4.3.2
@angular/core: 4.3.2
@angular/forms: 4.3.2
@angular/http: 4.3.2
@angular/platform-browser: 4.3.2
@angular/platform-browser-dynamic: 4.3.2
@angular/router: 4.3.2
@angular/cli: 1.2.3
@angular/compiler-cli: 4.3.2
@angular/language-service: 4.3.2

-------------

npm WARN @covalent/core@1.0.0-beta.6 requires a peer of @angular/common@^4.2.0 but none was installed.
npm WARN @covalent/core@1.0.0-beta.6 requires a peer of @angular/core@^4.2.0 but none was installed.
npm WARN @covalent/core@1.0.0-beta.6 requires a peer of @angular/forms@^4.2.0 but none was installed.
npm WARN @covalent/core@1.0.0-beta.6 requires a peer of @angular/http@^4.2.0 but none was installed.
npm WARN @covalent/core@1.0.0-beta.6 requires a peer of @angular/router@^4.2.0 but none was installed.
npm WARN @covalent/core@1.0.0-beta.6 requires a peer of @angular/cdk@^2.0.0-beta.8 but none was installed.
npm WARN @covalent/core@1.0.0-beta.6 requires a peer of @angular/material@^2.0.0-beta.8 but none was installed.

+ @covalent/core@1.0.0-beta.6
added 1 package and removed 882 packages in 65.165s

How to proceed ?

**Comment by SvenSeemann** [comment]
There might be some problems. I had the same thought for my project. Everything was build by using @angular/material and on some point I needed a stepper and discovered covalent.
Integrating all needed module and styles was no problem, but it seems to break the style of some components created before integrating covalent.

There are many small changes like setting another background-color to the sidenav content container, changing icon sizes, small displaces on some inputs. Haven't tracked down yet whether it's because some styles of @angular/flex-layout are overwritten or if it is something other.

**Comment by emoralesb05** [comment]
The styles clashing are now optional, so you can use covalent without the `platform.scss` or `covalent mixins`
