### ISSUE TITLE
Dynamic Forms Component

### ISSUE THREAD

**Issue by kyleledbetter** [Teradata/covalent#8]
Possibly based off https://github.com/formly-js/ng2-formly

**Comment by tycho01** [comment]
Ignoring implementations for a second, I'd be curious as to your stance toward JSON Schema as a potential base to generate forms from (or probably extended, as form libraries building off of it have generally done so far).
Pros would be existing adoption as a way to express valid (input) values, plus being fairly expressive.
(I'm not suggesting `angular-schema-form`, last time I checked they weren't there yet.)

**Comment by gnomeontherun** [comment]
We haven't put together a comprehensive plan for forms yet, so this is interesting input. We know that Formly is interesting, but it does focus on some different things (like being able to template with various types of UI libraries instead of just material). 

One example for our applications will be to have a JSON object define the form so it can dynamically generate all of the fields (I'm not familiar with the term OIM but this seems to be very similar). We have an existing API that defines these fields and generates a form, that we'll want to upgrade to work with Covalent. There is some discovery here for us to understand the constraints and challenges.

So yes, in general we're looking at a solution that marries together material form components and a JSON schema. If you have some design concepts or want to collaborate with this, we'd be happy to do some prototyping to see what we can figure out. This is likely one of those types of features that we'll build a simple solution that will need many iterations to polish for a more broad consumption.

**Comment by tycho01** [comment]
Yeah, I don't think anyone had heard of OIM, I also just found it on Formly's page linking to the above-mentioned podcast, which might have coined it. Since the podcast mentions multiple, them taking it from there probably also explains Formly's stance in not picking sides.

In reality it's a much smaller space though -- the Jsonary mentioned in the podcast seems to be a UI library (afaict on the level of `angular-schema-form`) for lack of a better term using JSON Schema itself, while that Metawidget appears to have a [JS port](https://github.com/metawidget/metawidget-js), but appears very simple afaict (apparently focusing solely on generating some inputs with default values, they don't seem concerned with validation). JSON Schema on the other hand has been used for validation purposes by some API specifications like [OpenAPI](https://openapis.org/) (née Swagger) and [JSON API](http://jsonapi.org/). The former was my use-case, to give context to my own bias. If you're coming from your own API as a use-case, you may consider checking them out too. :)

That isn't to say Formly doesn't have its own strengths compared to JSON Schema -- they were based on JS vs. JSON respectively, and the former obviously makes it easier to pass custom validation functions. That being said, existing form generation libraries have usually been inclined to add UI customization options on top, and I suppose at that point allowing JS objects (rather than just JSON serializations) so as to support custom validation functions should work just as well. I'll have to admit I'm not terribly familiar with Formly though, so there may be other relevant considerations. Any fields used in their [example](http://formly-js.github.io/ng2-formly/) (`className`, `label`, `placeholder`, `validation`, that `type` to pick the template) look pretty relevant though, so you shouldn't have to give up on functionality like that in a forms implementations.

API endpoints' request GET parameters essentially just form one object (i.e. some keyed values), which without nesting (-> no arrays/objects) is relatively straight-forward. I already needed more if just to allow specifying request headers though (-> object). This shows where it can get harder -- taking into account parts of JSON Schema like:

1. such arrays/objects (should use their own custom ng2 form controls),
2. schema recursion (requires a lazy approach, can't just pre-generate form controls),
3. wildcard schemas (`{}` / `type: 'any'`).

`react-jsonschema-form` and `angular-schema-form` both did 1, forgot about 2, neither did 3.
My own implementation so far consists of ng2 components + related form controls (for e.g. arrays, checkbox sets, objects either allowing schema swap on key change or structured to separate JSON Schema's `properties`/`patternProperties`/`additionalProperties`), lazily generated to solve 2.
Right now I'd just about tackled 3, which should allow generating UIs to edit the schema itself as well -- forms to generate forms to generate the input data you want, a bit like Kinto's [formbuilder](https://github.com/Kinto/formbuilder) in React land based on that `react-jsonschema-form`.

As you're saying, you'd probably manage with something simpler as well. I'll try to see if I can migrate to Covalent and split my UI generation off for you to try, but failing that, you can check my [components](https://github.com/tycho01/front/tree/master/app/comps/slim/input) and [controls](https://github.com/tycho01/front/tree/master/app/comps/slim/input/controls) for reference. I also just found this [angular2-schema-form](https://github.com/makinacorpus/angular2-schema-form) that may interest you as well.

**Comment by gnomeontherun** [comment]
I've had it in the back of my head that we'll essentially model an object that follows the properties set forth by HTML form elements. I think that will be most useful going forward, and allow us to keep it thin. You're raising a number of things that I suspect will have to be iterative releases to figure out.

This all really has to come in line with a REST API. Without clearing up the way the frontend and backend (regardless of platform) will both handle validation rules, I fear we're a few steps ahead on this discussion from our perspective.

**Comment by tycho01** [comment]
Fair enough, no rush on my part either.
Is there perhaps a place I could find documentation on your API(s)? I'd be interested in checking it out a bit further as well.

You mentioned doing a thin wrap of HTML form element properties -- which I guess might extend to wrapping Material components for their abstractions/additions. So [this page](https://teradata.github.io/covalent/style-guide/material-components) contains a form example:
```
<form>
  <md-input style="margin-right: 20px;" placeholder="Company (disabled)" disabled value="Google"></md-input>
  ...
</form>
```

From your description I'm imagining a JSON-like equivalent like this, probably missing your intention...:
```
<covalent-form elements="[
  { elem: 'md-input', props: { style: 'margin-right: 20px;', placeholder: 'Company (disabled)' disabled: null, value: 'Google', transcluded_text_and_elements: [] } },
  ...
]"></covalent-form>
```

**Comment by gnomeontherun** [comment]
We don't have any documentation publicly about the API yet. That is a similar JSON example, though I don't have the specifics in mind yet.

**Comment by tycho01** [comment]
Alright. Curious how things will develop. :)

**Comment by tycho01** [comment]
Based on your thin wrapper comment, you may be also interested in [this thread](https://github.com/angular/angular/issues/1034) for examples of a few similar projects.

**Comment by emoralesb05** [comment]
Proposed first iteration on schema (used as our internal projects):
```
{ 
  name: string, // unique name used to get value and name control in form
  type: string, // 'text' , 'number', 'date', 'boolean'
  max: number | ISODateStr, (only applicable when number or date)
  min: number | ISODateStr, (only applicable when number or date)
  minLength: number, (only applicable when text)
  maxLength: number, (only applicable when text)
  required: boolean, // require value to validate form
  default: any // initial value of component
}
```

**Comment by tycho01** [comment]
Guess that pretty much matches the html [input attributes](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input), so for internal implementation that should make things easy.
So for required/maxlength/minlength (note html uses lowercase on them) ng2 has [validator directives](https://angular.io/docs/ts/latest/api/#!?apiType=Directive) that'll stick on to the html attributes; for min/max I guess the number inputs may help restricting input values as well.

In the event you'd be willing to put up with the native Date input, [material2's `md-input`](https://github.com/angular/material2/blob/master/src/lib/input/README.md) might be close to meeting your stated initial requirements.

That said, they wouldn't do boolean either (delegated to checkbox/toggle), so you might just wrap them and swap input based on type.
I guess that also forms the core principle of my own project (particularly my [InputField](https://github.com/tycho01/front/tree/master/app/comps/slim/input/field) component, if not yet using Material2/Covalent), though I'd extended it to include array/object structures.

**Comment by emoralesb05** [comment]
Closing this since initial release will be in 0.10.

Please open a new issue for enhancements.
