### ISSUE TITLE
Paging component overrides styles of Angular Material Selects globally

### ISSUE THREAD

**Issue by repolevedavaj** [Teradata/covalent#872]
#### Bug Report

The Paging component does override some styles of the md-select component of Angular Material globally. This means that if you use both components on the same view, the md-selects are not displayed properly (missing underline, smaller font size).

#### What is the expected behavior?
The usage of the paging component on a view on which an md-select is used, should not affect the style of the select.

#### Which version of Angular and Material, and which browser and OS does this issue affect?
Angular Version: 4.3.6
Material Version: 2.0.0-beta.10
Covalent Core Version: 1.0.0-beta.7

**Comment by akrepon** [comment]
Hey,

Although I have a hotfix for this problem, I've came across this on the internet:

"Sass will no longer support /deep/ and >>> in any version of Sass; Chrome change the behavior of /deep/ since Chrome 60"

So /deep/ is apparently no longer supported by Chrome 60.

This is the version I am currently using.

I think this may be the problem. But I am not sure.

**Comment by aciccarello** [comment]
@akrepon Until the web standards bodies come up with a replacement `::ng-deep` can be used which will work with sass and Angular's emulated shadow dom styles.

See https://angular.io/guide/component-styles#deprecated-deep--and-ng-deep

**Comment by KevinGruber** [comment]
What is the status on that.
In my opinion it is a problem that the paging bar component is Style-Bleeding.

BR,
Kev

**Comment by emoralesb05** [comment]
Yeah, this is a bug we need to fix. Thanks for the heads up!
