### ISSUE TITLE
Design Patterns: Cards Pattern Inline Links Broken

### ISSUE THREAD

**Issue by jennmedellin** [Teradata/covalent#877]
Clicking the links in the paragraphs on the Design Patters > Cards page loads a blank page.

### Do you want to request a *feature* or report a *bug*?
Bug

##### Screenshots or link to CodePen/Plunker/JSfiddle
![links](https://user-images.githubusercontent.com/17860952/30500762-a3f5a9f2-9a14-11e7-9704-17f3b06bc23f.gif)

#### What is the expected behavior?
Loads page

#### Which version of Angular and Material, and which browser and OS does this issue affect?
Tested in Chrome, effects latest beta 7.

Did this work in previous versions of Angular / Material?
It's a new section.

**Comment by kyleledbetter** [comment]
It's bc you used href instead of routerLink
so here https://github.com/Teradata/covalent/blob/develop/src/app/components/design-patterns/cards/cards.component.html#L121
`<a href="/#/layouts/card-over" target="_blank">` should be `<a [routerLink]="['/layouts/card-over']">`

same issue here https://github.com/Teradata/covalent/blob/develop/src/app/components/design-patterns/cards/cards.component.html#L222
here https://github.com/Teradata/covalent/blob/develop/src/app/components/design-patterns/cards/cards.component.html#L336
here https://github.com/Teradata/covalent/blob/develop/src/app/components/design-patterns/alerts/alerts.component.html#L42
here https://github.com/Teradata/covalent/blob/develop/src/app/components/design-patterns/management-list/management-list.component.html#L45
here https://github.com/Teradata/covalent/blob/develop/src/app/components/design-patterns/management-list/management-list.component.html#L51

**Comment by emoralesb05** [comment]
Fixed
